### ISSUE TITLE
spec-v3, broekn views

### ISSUE THREAD

**Issue by martinschorb** [mobie/platybrowser-project#93]
Hi,

I get the following errors when trying to open views in Beta (spec-v3)

* mobie-paper "Figure1a" view:
```
Exception in thread "Thread-47" java.lang.NullPointerException
	at org.embl.mobie.viewer.plot.AnnotationKDTreeSupplier.initialiseDataPoints(AnnotationKDTreeSupplier.java:121)
	at org.embl.mobie.viewer.plot.AnnotationKDTreeSupplier.<init>(AnnotationKDTreeSupplier.java:71)
	at org.embl.mobie.viewer.plot.ScatterPlotView.updateScatterPlotSource(ScatterPlotView.java:161)
	at org.embl.mobie.viewer.plot.ScatterPlotView.show(ScatterPlotView.java:139)
	at org.embl.mobie.viewer.view.ViewManager.initScatterPlotView(ViewManager.java:164)
	at org.embl.mobie.viewer.view.ViewManager.show(ViewManager.java:637)
	at org.embl.mobie.viewer.view.ViewManager.show(ViewManager.java:271)
	at org.embl.mobie.viewer.ui.UserInterfaceHelper.lambda$null$14(UserInterfaceHelper.java:772)
	at java.lang.Thread.run(Thread.java:748)
```

* sbem-segmentation "tissue"view:
```
Exception in thread "PainterThread" java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
	at java.util.ArrayList.rangeCheck(ArrayList.java:657)
	at java.util.ArrayList.get(ArrayList.java:433)
	at org.embl.mobie.viewer.table.saw.TableSawAnnotationTableModel.annotation(TableSawAnnotationTableModel.java:199)
	at org.embl.mobie.viewer.annotation.DefaultAnnotationAdapter.createVariable(DefaultAnnotationAdapter.java:58)
	at org.embl.mobie.viewer.source.AnnotatedLabelSource.getSource(AnnotatedLabelSource.java:61)
	at org.embl.mobie.viewer.source.AbstractBoundarySource.getSource(AbstractBoundarySource.java:88)
	at bdv.viewer.render.VisibleSourcesOnScreenBounds.<init>(VisibleSourcesOnScreenBounds.java:149)
	at bdv.viewer.render.VisibleSourcesOnScreenBounds.<init>(VisibleSourcesOnScreenBounds.java:93)
	at bdv.viewer.render.MultiResolutionRenderer.paint(MultiResolutionRenderer.java:441)
	at bdv.viewer.ViewerPanel.paint(ViewerPanel.java:464)
	at bdv.viewer.render.PainterThread.run(PainterThread.java:82)
Exception in thread "AWT-EventQueue-0" java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
	at java.util.ArrayList.rangeCheck(ArrayList.java:657)
	at java.util.ArrayList.get(ArrayList.java:433)
	at org.embl.mobie.viewer.table.saw.TableSawAnnotationTableModel.annotation(TableSawAnnotationTableModel.java:199)
	at org.embl.mobie.viewer.annotation.DefaultAnnotationAdapter.createVariable(DefaultAnnotationAdapter.java:58)
	at org.embl.mobie.viewer.source.AnnotatedLabelSource.getSource(AnnotatedLabelSource.java:61)
	at org.embl.mobie.viewer.source.AbstractBoundarySource.getSource(AbstractBoundarySource.java:88)
	at bdv.viewer.overlay.MultiBoxOverlayRenderer.setViewerState(MultiBoxOverlayRenderer.java:172)
	at bdv.viewer.ViewerPanel.drawOverlays(ViewerPanel.java:510)
	at bdv.viewer.InteractiveDisplayCanvas.lambda$paintComponent$1(InteractiveDisplayCanvas.java:210)
	at java.util.concurrent.CopyOnWriteArrayList.forEach(CopyOnWriteArrayList.java:891)
	at bdv.viewer.InteractiveDisplayCanvas.paintComponent(InteractiveDisplayCanvas.java:210)
	at javax.swing.JComponent.paint(JComponent.java:1056)
	at javax.swing.JComponent.paintChildren(JComponent.java:889)
	at javax.swing.JComponent.paint(JComponent.java:1065)
	at javax.swing.JComponent.paintToOffscreen(JComponent.java:5210)
	at javax.swing.RepaintManager$PaintManager.paintDoubleBuffered(RepaintManager.java:1579)
	at javax.swing.RepaintManager$PaintManager.paint(RepaintManager.java:1502)
	at javax.swing.RepaintManager.paint(RepaintManager.java:1272)
	at javax.swing.JComponent._paintImmediately(JComponent.java:5158)
	at javax.swing.JComponent.paintImmediately(JComponent.java:4969)
	at javax.swing.RepaintManager$4.run(RepaintManager.java:831)
	at javax.swing.RepaintManager$4.run(RepaintManager.java:814)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:74)
	at javax.swing.RepaintManager.paintDirtyRegions(RepaintManager.java:814)
	at javax.swing.RepaintManager.paintDirtyRegions(RepaintManager.java:789)
	at javax.swing.RepaintManager.prePaintDirtyRegions(RepaintManager.java:738)
	at javax.swing.RepaintManager.access$1200(RepaintManager.java:64)
	at javax.swing.RepaintManager$ProcessingRunnable.run(RepaintManager.java:1732)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:758)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:74)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:728)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:205)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
Exception in thread "Thread-18" java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
	at java.util.ArrayList.rangeCheck(ArrayList.java:657)
	at java.util.ArrayList.get(ArrayList.java:433)
	at org.embl.mobie.viewer.table.saw.TableSawAnnotationTableModel.annotation(TableSawAnnotationTableModel.java:199)
	at org.embl.mobie.viewer.annotation.DefaultAnnotationAdapter.createVariable(DefaultAnnotationAdapter.java:58)
	at org.embl.mobie.viewer.source.AnnotatedLabelSource.getType(AnnotatedLabelSource.java:86)
	at org.embl.mobie.viewer.source.AnnotatedLabelSource.getType(AnnotatedLabelSource.java:40)
	at org.embl.mobie.viewer.source.AbstractBoundarySource.getType(AbstractBoundarySource.java:169)
	at org.embl.mobie.viewer.bdv.SourceNameRenderer.adaptSourceNames(SourceNameRenderer.java:119)
	at org.embl.mobie.viewer.bdv.SourceNameRenderer.transformChanged(SourceNameRenderer.java:95)
	at org.embl.mobie.viewer.view.ViewManager.show(ViewManager.java:286)
	at org.embl.mobie.viewer.ui.UserInterfaceHelper.lambda$null$14(UserInterfaceHelper.java:772)
	at java.lang.Thread.run(Thread.java:748)
```

* same for "ganglia"

**Comment by constantinpape** [comment]
I can reproduce the issues on Linux.

**Comment by tischi** [comment]
Should work with upload `1`. I will ping you somewhere else when I do this upload.

**Comment by martinschorb** [comment]
Confirm, works.
